[WIP] About Page
rhdevs/rhdevs-website pull request #12
Opened 2022-01-07 04:21 UTC by maximyam

![image](https://user-images.githubusercontent.com/88930900/148491218-db3be2e0-fae0-4078-ba28-2259879d58d8.png)

2022-01-07 04:23 UTC, maximyam commented
![](https://github.trello.services/images/mini-trello-icon.png) [about page](https://trello.com/c/6SKkI8zM/17-about-page)

2022-01-14 10:03 UTC, hui444 commented on src/pages/About/index.tsx
> +export default function AboutPage() {
Use 'About' instead

2022-01-14 10:03 UTC, hui444 commented on src/pages/About/styles/AboutPage.styled.ts
> +import styled from 'styled-components'
rename this file to About.styled.ts instead of AboutPage.styled.ts

2022-01-18 09:42 UTC, hui444 requested changes

2022-01-18 09:42 UTC, hui444 commented on src/components/styles/PageSection.styled.ts
> +  @keyframes fadeInUp {
consider using styled-components' keyframes instead

2022-01-18 09:42 UTC, hui444 commented on src/components/styles/PageSection.styled.ts
> +      transform: translate3d(0, 100%, 0);
would this be the same as `translateY(100%)` ?

2022-01-18 09:42 UTC, hui444 commented on src/components/styles/PageSection.styled.ts
> +      transform: translate3d(0, 100%, 0);
these too, would they be the same as `translateY(100%)` ?
see [link](https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function/translateY())

2022-01-18 09:42 UTC, hui444 commented on src/pages/About/styles/About.styled.ts
> +  z-index: -1;
is there a reason for this to be -1?

2022-01-18 09:42 UTC, hui444 commented on src/pages/About/styles/About.styled.ts
> +  padding-bottom: 200px;
consider using the shorthand for this instead? (`padding: 200px 0`)

2022-01-18 09:42 UTC, hui444 commented on src/pages/About/styles/About.styled.ts
> +  background: black;
consider using theme for this instead of 'black'

2022-01-25 02:27 UTC, hui444 commented on src/components/styles/PageSection.styled.ts
> +const fadeinuup = keyframes`
use camelCase instead

2022-01-25 02:27 UTC, hui444 commented on src/components/styles/PageSection.styled.ts
> +  animation-duration: 1s;
consider making this optional - use props to make it animate, also discuss w the person doing events page to see how they did it

2022-01-29 14:22 UTC, hui444 approved these changes
please fix the issues pointed out, else lgtm!

2022-01-29 14:22 UTC, hui444 commented on src/components/styles/PageSection.styled.ts
> +const fadeinUp = keyframes`
camelCase! fadeInUp

2022-01-29 14:22 UTC, hui444 commented on src/pages/About/styles/About.styled.ts
> +  padding: 50px 0 50px 0;
consider `padding: 50px 0;` instead

2022-01-29 16:37 UTC, merged