Email form
rhdevs/rhdevs-website pull request #48
Opened 2022-01-25 10:55 UTC by kktai1512

Use formspree

2022-01-25 10:56 UTC, kktai1512 commented
![](https://github.trello.services/images/mini-trello-icon.png) [contacts page](https://trello.com/c/5L55A75o/20-contacts-page)

2022-01-25 10:56 UTC, kktai1512 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Create contacts page FORM (with form to email service)](https://trello.com/c/0q0negd6/29-create-contacts-page-form-with-form-to-email-service)

2022-01-25 14:13 UTC, marcus-ong-qy commented on src/components/Button.tsx
> +      <AntdButton type="text" onClick={() => onClick()}>
same, `onClick={onClick}` should suffice

2022-01-25 14:16 UTC, marcus-ong-qy requested changes
Other than that the error messages are not showing on form submit, the form itself lgtm!

2022-01-28 12:13 UTC, marcus-ong-qy approved these changes

2022-01-28 12:15 UTC, marcus-ong-qy commented
lgtm! do consider reviewing my comments and merge soon!

2022-02-02 12:50 UTC, merged